_partial_: true # do not touch
_target_: algs.key_frame_det.frames_ratio.KeyFrameDetFramesRatio # do not touch
debug_level: 1
processing_res_width: 1280
processing_res_height: 720
threshold: 0.75
max_temporal_lag: 35
min_kf_distance: 25
lag_frames_aggregation: decaying